coreruleset/documentation

- content/configuring/false_positives_tuning.md
PR corrects spelling mistake:
"form" => "from".
> Correct spelling mistake

- content/rules/rules.md
The last title was **REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf.example** instead of **RESPONSE-999-EXCLUSION-RULES-AFTER-CRS.conf.example**
> Docs: Fix file naming

- content/configuring/plugins.md
This PR adds a link to the plugin registry at the bottom of the page where it's _mentioned_, but there's no link! I got frustrated and had to go searching for a link elsewhere in the document… There should be a link there.
> Add hyperlink to the plugin registry

- content/configuring/anomaly.md
- content/deployment/install.md
- content/deployment/quickstart.md
- content/resources/_index.md
- content/rules/creating.md
- content/rules/metadata.md
- content/rules/ruleid.md
- content/rules/rules.md
- content/rules/testing.md
This PR adds a note to the top of each page which has not been rewritten/updated/checked yet, so that readers know which parts of the documentation can currently be relied on to be up to date and accurate.
> Flag outdated content for readers

- content/deployment/install.md
- layouts/shortcodes/crsfiles.html
This is the power we have with hugo. This shortcode gets the files dynamically from GH, and receives a prefix for printing and the crs version.
Will remove the `.example` from files to and add them to the list. 🪄
> feat(shortcode): adds shortcode to get file names from GH

- content/development/useful_tools.md
PR standardises on the use of "libModSecurity". I thought I'd written more instances of it, but there's only one use to correct!
> Standardise on using "libModSecurity"

- content/concepts/plugins.md
- content/development/plugin_writing.md
- content/operation/containers.md
- content/operation/known_issues.md
- content/operation/log_handling.md
This PR:
- tidies up the known issues page
- adds basic content to all remaining empty pages
- splits the plugin documentation across the "Concepts" page and the previously empty "Writing Plugins" page
No new content, just fixes and tidying.
> Tidy up (pass 2)

- content/development/plugin_writing.md
- content/development/rule_writing.md
- content/development/sandbox.md
- content/development/testing.md
- content/development/useful_tools.md
PR adds a dummy Rule Writing page which points to the Contribution Guidelines page.
This makes the rule writing advice more visible, as a new visitor to the site might not find the rule writing tips which are buried within the Contribution Guidelines.
> Add dummy Rule Writing page pointing to Contrib.Gu

- content/development/contribution_guidelines.md
- content/development/regexp_assemble.md
- move the documentation for regexp-assemble from README file to online
docs.
- add section on possessive quantifiers to contribution guidelines
- add section on regular expression optimization to contribution
guidelines
- update Hugo theme
> chore(docs): add regexp-assemble docs

- content/development/contribution_guidelines.md
PR adds comments regarding how CRS represents forward slashes in regular expression patterns, as discussed at the previous project meeting.
> Write forward slash comments

- content/deployment/install.md
Removes mention to project honeypot RBL. Fixes https://github.com/coreruleset/coreruleset/issues/2508
> docs: remove reference to project honeypot

- content/development/sandbox.md
- add blocking mode docs
- add in/out anomaly score threshold docs
- moved all options to lowercase for coherence
> docs: update sandbox options

- content/development/contribution_guidelines.md
PR imports the change to the CRS repo regarding no use of ctl:auditLogParts (https://github.com/coreruleset/coreruleset/pull/3090).
> Sync ctl:auditLogParts change from CRS repository

- content/development/contribution_guidelines.md
> chore: update example tests in contribution docs

- content/operation/containers.md
PR removes the reference to the old, discontinued "ModSec only" containers.
The references to the current "CRS plus ModSec" containers remain. These are the only ones that should be used going forwards.
> Remove reference to the old vanilla ModSec contai.

- content/development/useful_tools.md
PR adds a new 'useful tool': the new coraza-httpbin container (https://github.com/jcchavezs/coraza-httpbin). Makes it easy to test CRS on Coraza, with no compilation of Coraza necessary!
> Add reference to coraza-httpbin

- content/development/contribution_guidelines.md
This PR fixes issue #69.
Adds a missing comment on the contribution guidelines page that was applied to the CRS repo version but not the documentation version. Also fixes a broken link to the ModSecurity Reference Manual.
> Add missing content and fix ref. man. link

- content/development/contribution_guidelines.md
PR follows change applied to the CRS repo version of this file, by amending the reference to `.data` files to `.ra`.
_Fixes issue #93._
> Amend .data file extension reference to .ra

- content/deployment/engine_integration_options.md
PR reworks the AWS WAF section, as we no longer believe that the AWS WAF "core rule set" is related to the actual OWASP CRS.
_Resolves issue #97_
> Rework AWS WAF section

- content/development/regex_assembly.md
fixed a typo where `diff` was used instead of `python`
> fix: update typo

- content/development/contribution_guidelines.md
PR corrects a single character typo which broke a hyperlink to the ModSecurity reference wiki regarding chain rules.
> Correct typo in link to ModSecurity reference wiki

- content/concepts/plugins.md
Based on a [Oct 2023 CRS team decision](https://github.com/coreruleset/coreruleset/issues/3280#issuecomment-1744217375), I have added the `SecCollectionTimeout` documentation to the plugin section. Not sure this is the best place, though.
Feedback, reviews and advice welcome.
> docs: document SecCollectionTimeout as part of plugin doc

- .github/workflows/gh-pages.yml
- move to standard pipeline
- after merging we remove the `gh-pages` branch, not needed anymore.
> feat: update build pipeline

- content/deployment/extended_install.md
Originally there was a Syntax Error in the "To trust the CRS project's public key:" section, where the command `gpg --edit-key` was misspelled as `gpg edit-key`. We fixed this by making the final syntax `gpg --edit-key`. 
Before:
----------------------------------------
```bash
gpg edit-key 
----------------------------------------
After:
----------------------------------------
changed to:
```bash
gpg --edit-key
---------------------------------------
> Update extended_install.md to fix syntax error of the `gpg --edit-key` command.

- .github/workflows/gh-pages.yml
Turns out dispatch needs to write contents. 🤷
> fix: add permissions to dispatch job

- content/development/crs_toolchain.md
Switching `With Existing Go Environment` with `With the Binary` so binary installation comes first.
> feat: changing order of crs-toolchain installation methods

- content/concepts/plugins.md
Documents how to conditionally enable plugins when using them in a multi-app environment, some users have issues with this as seen in https://github.com/coreruleset/coreruleset/issues/3655
When this is merged, I'll update all plugins readme to link to this.
> feat: conditionally enable plugins for multi-app environments

- content/development/testing.md
The command name of go-ftw in packages (e.g., for Linux distros) is `ftw`, not `go-ftw`.
> fix: add note to use ``ftw`` command over ``go-ftw`` for pre-compiled binaries

- content/rules/ruleid.md
We received a formal request from Yandex to reserve the 8,000,000-8,999,999 id range.
```
Hi dear collegues!
Hope you are doing well.
I'm Ruslan.
So now we are develop ruleset, based on SecLang.
According to documentation, gentle way - to reserve IDs in documentation if we plan to share our rules with extenal customers.
It will be great to reserve, for example,
ids: 8,000,000-8,999,999 - > Yandex
https://github.com/coreruleset/documentation/blob/main/content/rules/ruleid.md
Could you help me with it please?
BR, Ruslan S.
```
CC: @airween @dune73 for coordination.
> chore: add Yandex to ruleid

- .github/workflows/gh-pages.yml
- .github/workflows/test.yml
- config/_default/config.toml
- content/_index.md
- content/concepts/false_positives_tuning.md
- content/concepts/paranoia_levels.md
- content/concepts/plugins.md
- content/deployment/extended_install.md
- content/deployment/install.md
- content/development/contribution_guidelines.md
- content/development/crs_toolchain.md
- content/development/regex_assembly.md
- content/development/rule_writing.md
- content/development/testing.md
- content/development/useful_tools.md
- updates theme
- update hugo version
- needed to fix some relative references and config changes
> chore: update theme

- layouts/partials/content-footer.html
- layouts/partials/custom-footer.html
- split (duplicated) javascript tracking and image tracking
- fixes matomo breaking the content div
Fixes [coreruleset/website#305](https://github.com/coreruleset/website/issues/205)
> fix: matomo tracking

- renovate.json
The Hugo theme is updated pretty regularly on the main branch. Reduce noise by updating the theme once per month only.
> chore: update Hugo theme once per month only

- content/concepts/_index.md
- content/deployment/_index.md
- content/development/_index.md
- content/development/testing.md
- content/miscellaneous/_index.md
- content/operation/_index.md
- content/resources/_index.md
- content/rules/_index.md
- content/rules/rules.md
The `title` attribute for Hugo already defines the `h1` for a page. No need for an additional `h1` in markdown.
> fix: remove duplicate h1 tags

- content/_index.md
- content/deployment/install.md
- add rfdos docs as a warning in the install page
- document rfdos relevant references and tests
Fixes #165
> docs: add rfdos warning

- content/development/testing.md
- replace httpbin for albedo
- remove prefix in bash code
- keep up to date with response testing
- consistency
> docs: add reference to albedo for testing

- content/concepts/false_positives_tuning.md
- update false positives tuning
- add quadrant
- remove reference to old exclusion rules and add plugins
- update docs
> refactor: update false positives tuning

- content/development/testing.md
Added `TX` variable `total_arg_length` with value `64000` because rule [920390](https://github.com/coreruleset/coreruleset/blob/main/rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf#L881) uses that and its [test](https://github.com/coreruleset/coreruleset/blob/main/tests/regression/tests/REQUEST-920-PROTOCOL-ENFORCEMENT/920390.yaml#L29) expects it. Without that a "regular" test is failed.
CRS test uses [modsecurity-crs-docker](https://github.com/coreruleset/modsecurity-crs-docker) image where [activate-rules.sh](https://github.com/coreruleset/modsecurity-crs-docker/blob/a5c93c7416bf3f9b9f6d55056a005399eecdddf4/src/opt/modsecurity/activate-rules.sh#L92) sets that variable.
> fix: add 'tx.total_arg_length' to rule 900005 for testing

- content/development/testing.md
Added `TX` variable `max_num_args` with value `255` because rule [920390](https://github.com/coreruleset/coreruleset/blob/main/rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf#L881) uses that and its [test](https://github.com/coreruleset/coreruleset/blob/main/tests/regression/tests/REQUEST-920-PROTOCOL-ENFORCEMENT/920390.yaml#L29) expects it. Without that a "regular" test is failed.
CRS test uses [modsecurity-crs-docker](https://github.com/coreruleset/modsecurity-crs-docker) image where [activate-rules.sh](https://github.com/coreruleset/modsecurity-crs-docker/blob/a5c93c7416bf3f9b9f6d55056a005399eecdddf4/src/opt/modsecurity/activate-rules.sh#L78) sets that variable.
> fix: add 'tx.max_num_args' to rule 900005 for testing

- renovate.json
Hugo 0.146.0 includes a new templating engine that isn't yet supported by the Relearn theme.
> chore: pin Hugo to 0.145.0
