content/configuring/paranoia_levels.md

This PR imports and reworks the content from the recent paranoia levels blog post.

Import and rework the paranoia levels blog post

---

README.md

Adds useful information for outside contributors.

README: add fork tip

---

content/rules/ruleid.md

I'm not certain this is the correct link.  I've been trying to find the list of Akamai's rule IDs but don't see any docs anywhere.

Update link to Akamai WAF

---

config/_default/config.toml
content/deployment/install.md
content/deployment/quickstart.md

- add config parameter with latest release version
- add verification using gpg
Fixes https://github.com/coreruleset/coreruleset/issues/2435.

docs: add crs verification steps

---

content/deployment/engine_integration_options.md

@fzipi I've split out some of the content for what I think is a clearer layout when rendered in Hugo.
I've also tweaked a few sentences and added some formatting.
Do these changes look okay to you?

Tweaks to engine and integration content

---

content/deployment/engine_integration_options.md

Updated engine and integrations. Not much but a nice base.

docs: update engine and integration

---

content/development/contribution_guidelines.md

PR adds missing quote marks to the contribution guidelines page.

Add missing quote marks

---

content/development/contribution_guidelines.md

Reverts coreruleset/documentation#31

Revert "Update contributing.md"

---

content/development/useful_tools.md

Add FTW and Go-FTW to useful tools page

---

content/development/contribution_guidelines.md

Fix missing commit from #33 and subsequent reversion.

Fix missing commit

---

content/development/_index.md
content/miscellaneous/_index.md
content/operation/_index.md
content/resources/_index.md
content/rules/rules.md

add numbering to all menu items

---

content/operation/known_issues.md
content/rules/_index.md

Imported known issues from repo and website into the documentation (plus fixed numbering)

Known issues

---

content/_index.md
content/resources/_index.md

PR prepares the front page to be the new landing page for 'Documentation' on coreruleset.org.

New old landing page

---

content/deployment/install.md
content/deployment/quick_start.md

Following review, PR tweaks language, breaks up slightly differently, and makes content consistent with other existing pages.

Install update amendments

---

.github/workflows/gh-pages.yml
.github/workflows/test.yml
README.md

Update the base theme that contains many fixes.

feat(theme): update relearn theme

---

content/deployment/engine_integration_options.md

I've extended this quite a bit. Please review carefully before merging.
@fzipi: I have taken on some of your text, but may have dropped some of it as well. Please check.
@RedXanadu: Please review (-> expand and refine) the mentioning of LoadBalancer.org. I did this so Kemp was not the only listing in this category. Well thinking of, I could also add AVI...

Extended the engine and integration options

---

content/development/contribution_guidelines.md

Amend contribution guidelines addition to follow the style and tone of the rest of the document.

Amend contribution guidelines addition

---

content/development/contribution_guidelines.md

PR imports the Contribution Guidelines changes about rule operators, from CRS repo PR https://github.com/coreruleset/coreruleset/pull/2541.

Update contribution guidelines from CRS repository

---

content/_index.md

Update link. To be merged after https://github.com/coreruleset/coreruleset/pull/2606.

fix(url): update changes file link

---

content/operation/kubernetes_ingress.md
content/operation/log_handling.md

Style and tone tweaks to fit in with the rest of the "reference material"-style content.

Tweak Kubernetes ingress controller content

---

content/operation/kubernetes_ingress.md
content/operation/log_handling.md

Based on comments in the slack channel, added this short k8s guidance.

feat(k8s): add nginx ingress documentation

---

content/development/contribution_guidelines.md
content/development/regexp_assemble.md

PR makes:
- language and layout tweaks for consistency with the rest of the documentation
- one or two of minor (non-technical) corrections.

Regexp assemble tweaks

---

content/development/regexp_assemble.md

See https://github.com/coreruleset/coreruleset/pull/2767

feat (regexp-assemble): Document new `~` symbol

---

content/development/regexp_assemble.md

Improve description of `~` and `@` flags of the cmdline processor.

chore: update regexp-assemble docs

---

content/development/regexp_assemble.md

PR re-applies the fix from #64 which got overwritten.

Re-correct capitalisation and pluralisation

---

content/deployment/engine_integration_options.md

Update google cloud armor offering.

chore: update google cloud armor offering

---

config/_default/config.toml
content/deployment/engine_integration_options.md
content/development/testing.md

fix(version): update dev version and latest release

---

content/development/crs_toolchain.md
content/development/regex_assembly.md

PR brings the new crs-toolchain pages and changes in line with the existing pages. Corrects minor errors.

Crs toolchain fixes

---

content/operation/known_issues.md

This PR closes CRS's issue [#2884](https://github.com/coreruleset/coreruleset/issues/2884).

Disable compressed response body in modsec3 - add documentation

---

content/_index.md

PR implements OWASP's newly announced name change (web => worldwide).

Implement OWASP name change

---

content/development/testing.md

This PR explains how to use `go-ftw` with docker and/or own instance.

docs: Added go-ftw test

---

content/development/testing.md

docs: added missing backslash

---

content/concepts/anomaly_scoring.md
content/concepts/false_positives_tuning.md
content/deployment/install.md
content/development/contribution_guidelines.md
content/operation/known_issues.md
content/rules/creating.md

chore: update modsec url

---

content/development/regex_assembly.md

Added the extension's location to the setup section of regexp-assembly tool

Added VSCode syntax highlight extension's location

---

.github/workflows/gh-pages.yml

- send signal to website repo about documentation update
- website will embed documentation updated below `/docs` folder

feat: dispatch event when documentation is updated

---

.github/workflows/gh-pages.yml

fix: auth token

---

.github/workflows/test.yml

Adds [lychee](https://github.com/lycheeverse/lychee) for link checking in markdown files.
See https://github.com/coreruleset/documentation/actions/runs/8556168272.

feat: add link checker

---

content/deployment/install.md

fix: plugin link

---

.github/pull_request_template.md
.gitignore
CONTRIBUTING.md
README.md

- Add .gitignore and a PR template
- Update README for readability
- Add contribution reference

feat: few updates and repository reference syncs 

---

.github/workflows/gh-pages.yml
.github/workflows/test.yml

- fix package name for renovatebot
- update them automatically

fix: update package name for renovate config

---

content/deployment/engine_integration_options.md

- adds new OWASP stewardship of modsecurity
- remove old comments
- keep up to date
Fixes #115

fix: update modsecurity stewardship

---

content/deployment/install.md
content/development/testing.md
content/operation/known_issues.md

- update docker compose install
- add more relevant text for go-ftw binary install
- remove unsupported, unmaintained python ftw text.

fix: update docker compose and go-ftw packages install

---

content/1-getting-started/1-4-engine_integration_options.md

Edgio, formerly Edgecast, no longer exists since January 2024.

chore: remove Edgecast

---

content/1-getting-started/1-4-engine_integration_options.md

- update engine integration
- add owasp modsecurity
- update links

fix: update engine integration
